### ISSUE TITLE
Idempotency

### ISSUE THREAD

**Issue by jorbor** [ahbuddha/Inventory#3]
Can you elaborate on this?

`The put and delete methods are supposed to be idempotent but I decided that if the user is trying to do something that doesn’t exist, i.e. removing an item that is not there, they should be notified.`

Does sending a notification when an item is removed, or returning a different status code when an item doesn't exist, make the method not idempotent?

**Comment by ahbuddha** [comment]
From my understanding of idempotent, whether the item exists or not, as with the PUT method, the returning status code should always be the same.

To quote Gregor Roth:
"The PUT method is idempotent. An idempotent method means that the result of a successful performed request is independent of the number of times it is executed."
