### ISSUE TITLE
Decouple notification

### ISSUE THREAD

**Issue by jorbor** [ahbuddha/Inventory#4]
How would you feel about decoupling notification from twilio? Is it a good idea, and how would you go about it?

**Comment by ahbuddha** [comment]
I realize after a day or so of creating this project that naming the notification process twilio is too specific. The current design, i believe, lends itself to good data abstraction, any type of notification whether it be sms, email etc can be easily changed not effecting those calling it.

In short, I would rename the file _twilio to _notify and if there are more then one type of notification to send (i.e. sending both sms and an email) i would separate those into their own modules.
