### ISSUE TITLE
Date format

### ISSUE THREAD

**Issue by jorbor** [ahbuddha/Inventory#5]
Can you forsee any issues using the "yyyy/mm/dd" date format?

**Comment by ahbuddha** [comment]
The date object in JavaScript is pretty lenient in the variety of date formats it can handle as a parameter when creating a new object.
When creating a new item, the add method calls the "isValidDate" function which checks to see if it is valid. If not, it sets the expiration to a year from the current date. I just put the static data date string in that format for my own ease of use.
