### ISSUE TITLE
Expiration flow

### ISSUE THREAD

**Issue by jorbor** [ahbuddha/Inventory#6]
The readme describes the expiration process:
1. Something calls `get /expired-item`
2. Background job calls `delete /inventory/:label` for each expired item

Couple of questions:
1. Are there issues calling twilio for each expired item every time `get /expired-item` is called?
1. How will this scale when there are many items in the system? Or if the background job hasn't run for a while?

**Comment by ahbuddha** [comment]
The more sms's sent the greater the cost (each sms costs 0.0075) but this is pretty marginal. The reason you would want to do it individually, is that it will be easier to read for the user. Sending all of them as one big txt message could be hard to delineate and there are also limitations to sms message size.

Sense the work is done by a background process, this will scale quite well. When the number of items exceeds some amount, so can easily increase the processing power of the outside job manager to handle larger and larger numbers of data.

**Comment by ahbuddha** [comment]
After reexamining the code again, I just realized that the `get /expired-item` sends an array to the notification method. So it is in fact sending a string of comma separated expired item labels. I believe twilio will take care of sending large sms messages. But in the future a global flag should be created to decide whether or not to send individually or all at once.
